apiVersion: v1
kind: Secret
metadata:
  name: cipher-secrets
  namespace: cipher
type: Opaque
stringData:
  JWT_SECRET_KEY:       "change-this-to-64-char-random-string-in-production"
  STRIPE_SECRET_KEY:    "sk_test_placeholder"
  STRIPE_WEBHOOK_SECRET:"whsec_placeholder"
  STRIPE_PRICE_STARTER: "price_placeholder"
  STRIPE_PRICE_PRO:     "price_placeholder"
  GITHUB_WEBHOOK_SECRET:"dev-secret"
  SENDGRID_API_KEY:     "SG.placeholder"
  POSTGRES_PASSWORD:    "cipher_pass"
