apiVersion: v1
kind: ConfigMap
metadata:
  name: cipher-config
  namespace: cipher
data:
  APP_ENV:                   "production"
  DATABASE_URL:              "postgresql+asyncpg://cipher:cipher_pass@postgres-service:5432/cipher_db"
  REDIS_URL:                 "redis://redis-service:6379/0"
  KAFKA_BOOTSTRAP_SERVERS:   "kafka-service:9092"
  MLFLOW_TRACKING_URI:       "http://mlflow-service:5000"
  INFERENCE_SERVICE_URL:     "http://inference-service:8000"
  AWS_REGION:                "ap-south-1"
  S3_BUCKET_LOGS:            "cipher-logs-prod"
  S3_BUCKET_MODELS:          "cipher-models-prod"
  JWT_ALGORITHM:             "HS256"
  JWT_EXPIRE_MINUTES:        "10080"
  FRONTEND_URL:              "https://cipher.dev"
